//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppResDir {
            get {
                return ((string)(this["AppResDir"]));
            }
            set {
                this["AppResDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetupXmlPath {
            get {
                return ((string)(this["SetupXmlPath"]));
            }
            set {
                this["SetupXmlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MOmode {
            get {
                return ((bool)(this["MOmode"]));
            }
            set {
                this["MOmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationStartupPath {
            get {
                return ((string)(this["ApplicationStartupPath"]));
            }
            set {
                this["ApplicationStartupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoShortcutRegistryCheckBoxChecked {
            get {
                return ((bool)(this["AutoShortcutRegistryCheckBoxChecked"]));
            }
            set {
                this["AutoShortcutRegistryCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MOmodeDataFilesBak {
            get {
                return ((string)(this["MOmodeDataFilesBak"]));
            }
            set {
                this["MOmodeDataFilesBak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModdedDataFilesListFile {
            get {
                return ((string)(this["ModdedDataFilesListFile"]));
            }
            set {
                this["ModdedDataFilesListFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VanillaDataFilesListFile {
            get {
                return ((string)(this["VanillaDataFilesListFile"]));
            }
            set {
                this["VanillaDataFilesListFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MOToStandartConvertationOperationsListFile {
            get {
                return ((string)(this["MOToStandartConvertationOperationsListFile"]));
            }
            set {
                this["MOToStandartConvertationOperationsListFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentGameListIndex {
            get {
                return ((int)(this["CurrentGameListIndex"]));
            }
            set {
                this["CurrentGameListIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool INITDone {
            get {
                return ((bool)(this["INITDone"]));
            }
            set {
                this["INITDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BepinExCfgPath {
            get {
                return ((string)(this["BepinExCfgPath"]));
            }
            set {
                this["BepinExCfgPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MOSelectedProfileDirName {
            get {
                return ((string)(this["MOSelectedProfileDirName"]));
            }
            set {
                this["MOSelectedProfileDirName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XUAiniPath {
            get {
                return ((string)(this["XUAiniPath"]));
            }
            set {
                this["XUAiniPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentGameIsChanging {
            get {
                return ((bool)(this["CurrentGameIsChanging"]));
            }
            set {
                this["CurrentGameIsChanging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetModOrganizerINISettingsForTheGame {
            get {
                return ((bool)(this["SetModOrganizerINISettingsForTheGame"]));
            }
            set {
                this["SetModOrganizerINISettingsForTheGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtraSettingsInitOnLoadIsInAction {
            get {
                return ((bool)(this["ExtraSettingsInitOnLoadIsInAction"]));
            }
            set {
                this["ExtraSettingsInitOnLoadIsInAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MOIsNew {
            get {
                return ((bool)(this["MOIsNew"]));
            }
            set {
                this["MOIsNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationProductName {
            get {
                return ((string)(this["ApplicationProductName"]));
            }
            set {
                this["ApplicationProductName"] = value;
            }
        }
    }
}
